version: "3"
services:
  app:
    container_name: login_microservice
    build: "."
    ports:
      - 5000:5000
    restart: always
    depends_on: 
      - redis

  redis:
    image: 'redis:latest'
    container_name: login_redis_microservice
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'