version: "3"
services:
  app:
    container_name: login_microservice
    build: "."
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5002:5000
    restart: always
    depends_on:
      - redis
    networks:
      - fiuber-network

  redis:
    image: 'redis:latest'
    container_name: login_redis_microservice
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - fiuber-network

networks:
  fiuber-network:
    driver: bridge
    name: fiuber-network
